### ISSUE TITLE
Add Bundle Size Changes GitHub action

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#163]
Add this cool GitHub action I found that displays bundle size changes in each PR just for the record.

Code:
```yaml
name: Compressed Size

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
