### ISSUE TITLE
Regression: Internal Server Error(s) when creating builds via GraphQL API

### ISSUE THREAD

**Issue by sio** [cirruslabs/cirrus-ci-web#426]
In the past few days creating new builds via GraphQL API results a nondescript `Internal Server Error(s) while executing query`.

Looks like recent refactoring of API schema (#425, moving from `github*` parameter names to `owner*`) has left some things in a broken state. Unfortunately the error message is intentionally opaque, so only Cirrus staff can help with further troubleshooting.

The following query with similar payload was working correctly before (last known successful usage: January 14).

Sample API query:

```graphql
mutation ScheduleCustomBuild($config: String!,
                             $repo: ID!,
                             $branch: String!,
                             $mutation_id: String!) {
    createBuild(
        input: {
            repositoryId: $repo,
            branch: $branch,
            clientMutationId: $mutation_id,
            configOverride: $config
        }
    ) {
        build {
            id
            status
        }
    }
}
```

Parameters:

```yaml
repo: '4749235174244352'
branch: master
mutation_id: cirrus-run job 385065
config: |-
  test_task:
    name: Simple noop task
    container:
      image: debian:stable-slim
    test_script: echo Hello World
```

Response:

```json
{
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query",
      "locations": []
    }
  ],
  "data": {
    "createBuild": null
  }
}
```
